### ISSUE TITLE
More options

### ISSUE THREAD

**Issue by NOTgithub** [adamfranco/Saved-Passwords-Button#1]
Please add configurable preference options to:
1) hide/ show passwords (value ´show´ by default)
2) search passwords of either all (sub)domains or only (sub)domain of current tab (´current tab´ by default)
3) add/ remove red colored ´Tools´ menu-item (value ´remove´ by default)
4) add/ remove button to Navigation toolbar (value ´add´ by default)

**Comment by adamfranco** [comment]
Thanks for the feedback, I'm unclear what you mean by (3), could you clarify?

**Comment by NOTgithub** [comment]
You are welcome. Thanks for developing this add-on. I love the concept of the add-on, but IMO it would become really useful/ perfect after implementing the features I suggested.

ad 3) Currently, the add-on adds a red (why?) menu-item (under 'Tools'), titled 'Saved Passwords...". This item should be optional, because it:
a) is not very useful, since there exists already other ways to access the saved password: via the original way (via Tools -> Options -> Security -> Saved Passwords button) and via the optional toolbar button.
b) attracts too much attention from unauthorized users who accidentally do get access to my webbrowser.

Hope this helps.

**Comment by adamfranco** [comment]
For the upcoming 1.2 release I have:
- Set the current tab's host-name as the default search when opening the window (2).
- Removed the Tools menu-item (3). This was an artifact of following the extension building tutorial and not really necessary.
- Added an install script to add the button to the toolbar on install (4).

At this time I won't be adding (1) since I can't figure out how to work with the functions in <a href="chrome://passwordmgr/content/passwordManager.js">chrome://passwordmgr/content/passwordManager.js</a>. I'll keep it in mind for future improvement though. Thanks for the feedback.

**Comment by NOTgithub** [comment]
Just now, my Firefox updated the add-on automatically. After that I noticed the changes. Thanks a lot! :-) Much more user-friendly now. Maybe, we should set the status of this issue back to "open", as sub 4 remains unresolved still.
